apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anki-sync-server-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: anki-sync.haijin666.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: anki-sync-server-service
            port:
              number: 8080