apiVersion: v1
kind: Service
metadata:
  name: anki-sync-server-service
spec:
  selector:
    app: anki-sync-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP