apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qinglong-ingress
spec:
  rules:
  - host: qinglong.haijin666.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qinglong-service
            port:
              number: 80