apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tuwunel-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: tuwunel.haijin666.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tuwunel
                port:
                  number: 6167
